### ISSUE TITLE
Minor typo. `wrappedComponenDisplayName` is missing 't' in 'Component'.

### ISSUE THREAD

**Issue by gitgrimbo** [slively/fullstack-typescript#1]
https://github.com/slively/fullstack-typescript/blob/bf883a4549c18129714232ccc6bc6139657d5e2e/ui/src/lib/withObservable.tsx#L19

Minor typo. `wrappedComponenDisplayName` is missing 't' in 'Component'.

**Comment by slively** [comment]
thank you, fixed!
