### ISSUE TITLE
untyped in latest typescript

### ISSUE THREAD

**Issue by lifeiscontent** [slively/fullstack-typescript#2]
https://github.com/slively/fullstack-typescript/blob/bf883a4549c18129714232ccc6bc6139657d5e2e/ui/src/lib/combineLatestObj.ts#L33

hey, I'm not good enough with typescript + rxjs but do you know the reason why this is untyped @slively ?

**Comment by slively** [comment]
Good question. The function is meant to take a list of `Partial<T>` and reduce them into a full `T` interface. That means the result is actually a `Partial<T>` until the very end. I think the current implementation is a bit of laziness around defining that behavior as it just takes a list of objects and casts them to T when done reducing. This alternative might be more clear:

```typescript
function reduceObservablesToValue<T>(values: Partial<T>[]): T {
	const result: Partial<T> = {};

	return values.reduce(
		(acc: Partial<T>, obs: Partial<T>) => {
			Object.keys(obs).forEach((key: string) => {
				acc[key] = obs[key];
			});

			return acc;
		},
		result
	) as T;
}
```
